[project]
name = "app-browser-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "flask>=3.1.2",
    "opencv-python>=4.12.0.88",
]
